# Generated by Django 5.2.1 on 2025-07-03 22:15

import django.db.models.deletion
import django_countries.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('max_products', models.IntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(default='BO', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.plan')),
                ('rubro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='America/La_Paz', max_length=50)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('currency', models.CharField(default='BOB', max_length=10)),
                ('tax_enabled', models.BooleanField(default=False)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('alerts_stock', models.BooleanField(default=True)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('notification_email', models.BooleanField(default=False)),
                ('auto_update_price_on_purchase', models.BooleanField(default=False)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.0'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
            ],
        ),
    ]
